/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppMembersRouteImport } from './routes/_authenticated/app.members'
import { Route as AuthenticatedAppUnitsRouteImport } from './routes/_authenticated/app.units'
import { Route as AuthenticatedAppWorkspaceRouteImport } from './routes/_authenticated/app.workspace'
import { Route as AuthenticatedAppWorkspacesRouteImport } from './routes/_authenticated/app.workspaces'
import { Route as AuthenticatedAppUnitUnitIdRouteImport } from './routes/_authenticated/app.unit.$unitId'
import { Route as AuthenticatedAppUnitUnitIdIndexRouteImport } from './routes/_authenticated/app.unit.$unitId.index'
import { Route as AuthenticatedAppUnitUnitIdAccessRouteImport } from './routes/_authenticated/app.unit.$unitId.access'
import { Route as AuthenticatedAppUnitUnitIdActionsRouteImport } from './routes/_authenticated/app.unit.$unitId.actions'
import { Route as AuthenticatedAppUnitUnitIdAlertsRouteImport } from './routes/_authenticated/app.unit.$unitId.alerts'
import { Route as AuthenticatedAppUnitUnitIdBillingRouteImport } from './routes/_authenticated/app.unit.$unitId.billing'
import { Route as AuthenticatedAppUnitUnitIdControlRoomRouteImport } from './routes/_authenticated/app.unit.$unitId.control-room'
import { Route as AuthenticatedAppUnitUnitIdFlowsRouteImport } from './routes/_authenticated/app.unit.$unitId.flows'
import { Route as AuthenticatedAppUnitUnitIdSystemsRouteImport } from './routes/_authenticated/app.unit.$unitId.systems'
import { Route as AuthenticatedAppUnitUnitIdSystemsIndexRouteImport } from './routes/_authenticated/app.unit.$unitId.systems.index'
import { Route as AuthenticatedAppUnitUnitIdSystemsSystemIdRouteImport } from './routes/_authenticated/app.unit.$unitId.systems.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMembersRoute = AuthenticatedAppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUnitsRoute = AuthenticatedAppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkspaceRoute =
  AuthenticatedAppWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWorkspacesRoute =
  AuthenticatedAppWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUnitUnitIdRoute =
  AuthenticatedAppUnitUnitIdRouteImport.update({
    id: '/unit/$unitId',
    path: '/unit/$unitId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUnitUnitIdIndexRoute =
  AuthenticatedAppUnitUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdAccessRoute =
  AuthenticatedAppUnitUnitIdAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdActionsRoute =
  AuthenticatedAppUnitUnitIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdAlertsRoute =
  AuthenticatedAppUnitUnitIdAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdBillingRoute =
  AuthenticatedAppUnitUnitIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdControlRoomRoute =
  AuthenticatedAppUnitUnitIdControlRoomRouteImport.update({
    id: '/control-room',
    path: '/control-room',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdFlowsRoute =
  AuthenticatedAppUnitUnitIdFlowsRouteImport.update({
    id: '/flows',
    path: '/flows',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdSystemsRoute =
  AuthenticatedAppUnitUnitIdSystemsRouteImport.update({
    id: '/systems',
    path: '/systems',
    getParentRoute: () => AuthenticatedAppUnitUnitIdRoute,
  } as any)
const AuthenticatedAppUnitUnitIdSystemsIndexRoute =
  AuthenticatedAppUnitUnitIdSystemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppUnitUnitIdSystemsRoute,
  } as any)
const AuthenticatedAppUnitUnitIdSystemsSystemIdRoute =
  AuthenticatedAppUnitUnitIdSystemsSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => AuthenticatedAppUnitUnitIdSystemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/members': typeof AuthenticatedAppMembersRoute
  '/app/units': typeof AuthenticatedAppUnitsRoute
  '/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/app/workspaces': typeof AuthenticatedAppWorkspacesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/unit/$unitId': typeof AuthenticatedAppUnitUnitIdRouteWithChildren
  '/app/unit/$unitId/access': typeof AuthenticatedAppUnitUnitIdAccessRoute
  '/app/unit/$unitId/actions': typeof AuthenticatedAppUnitUnitIdActionsRoute
  '/app/unit/$unitId/alerts': typeof AuthenticatedAppUnitUnitIdAlertsRoute
  '/app/unit/$unitId/billing': typeof AuthenticatedAppUnitUnitIdBillingRoute
  '/app/unit/$unitId/control-room': typeof AuthenticatedAppUnitUnitIdControlRoomRoute
  '/app/unit/$unitId/flows': typeof AuthenticatedAppUnitUnitIdFlowsRoute
  '/app/unit/$unitId/systems': typeof AuthenticatedAppUnitUnitIdSystemsRouteWithChildren
  '/app/unit/$unitId/': typeof AuthenticatedAppUnitUnitIdIndexRoute
  '/app/unit/$unitId/systems/$systemId': typeof AuthenticatedAppUnitUnitIdSystemsSystemIdRoute
  '/app/unit/$unitId/systems/': typeof AuthenticatedAppUnitUnitIdSystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/members': typeof AuthenticatedAppMembersRoute
  '/app/units': typeof AuthenticatedAppUnitsRoute
  '/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/app/workspaces': typeof AuthenticatedAppWorkspacesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/unit/$unitId/access': typeof AuthenticatedAppUnitUnitIdAccessRoute
  '/app/unit/$unitId/actions': typeof AuthenticatedAppUnitUnitIdActionsRoute
  '/app/unit/$unitId/alerts': typeof AuthenticatedAppUnitUnitIdAlertsRoute
  '/app/unit/$unitId/billing': typeof AuthenticatedAppUnitUnitIdBillingRoute
  '/app/unit/$unitId/control-room': typeof AuthenticatedAppUnitUnitIdControlRoomRoute
  '/app/unit/$unitId/flows': typeof AuthenticatedAppUnitUnitIdFlowsRoute
  '/app/unit/$unitId': typeof AuthenticatedAppUnitUnitIdIndexRoute
  '/app/unit/$unitId/systems/$systemId': typeof AuthenticatedAppUnitUnitIdSystemsSystemIdRoute
  '/app/unit/$unitId/systems': typeof AuthenticatedAppUnitUnitIdSystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/members': typeof AuthenticatedAppMembersRoute
  '/_authenticated/app/units': typeof AuthenticatedAppUnitsRoute
  '/_authenticated/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/_authenticated/app/workspaces': typeof AuthenticatedAppWorkspacesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/unit/$unitId': typeof AuthenticatedAppUnitUnitIdRouteWithChildren
  '/_authenticated/app/unit/$unitId/access': typeof AuthenticatedAppUnitUnitIdAccessRoute
  '/_authenticated/app/unit/$unitId/actions': typeof AuthenticatedAppUnitUnitIdActionsRoute
  '/_authenticated/app/unit/$unitId/alerts': typeof AuthenticatedAppUnitUnitIdAlertsRoute
  '/_authenticated/app/unit/$unitId/billing': typeof AuthenticatedAppUnitUnitIdBillingRoute
  '/_authenticated/app/unit/$unitId/control-room': typeof AuthenticatedAppUnitUnitIdControlRoomRoute
  '/_authenticated/app/unit/$unitId/flows': typeof AuthenticatedAppUnitUnitIdFlowsRoute
  '/_authenticated/app/unit/$unitId/systems': typeof AuthenticatedAppUnitUnitIdSystemsRouteWithChildren
  '/_authenticated/app/unit/$unitId/': typeof AuthenticatedAppUnitUnitIdIndexRoute
  '/_authenticated/app/unit/$unitId/systems/$systemId': typeof AuthenticatedAppUnitUnitIdSystemsSystemIdRoute
  '/_authenticated/app/unit/$unitId/systems/': typeof AuthenticatedAppUnitUnitIdSystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/control-room'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/app'
    | '/app/billing'
    | '/app/members'
    | '/app/units'
    | '/app/workspace'
    | '/app/workspaces'
    | '/app/'
    | '/app/unit/$unitId'
    | '/app/unit/$unitId/access'
    | '/app/unit/$unitId/actions'
    | '/app/unit/$unitId/alerts'
    | '/app/unit/$unitId/billing'
    | '/app/unit/$unitId/control-room'
    | '/app/unit/$unitId/flows'
    | '/app/unit/$unitId/systems'
    | '/app/unit/$unitId/'
    | '/app/unit/$unitId/systems/$systemId'
    | '/app/unit/$unitId/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/control-room'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/app/billing'
    | '/app/members'
    | '/app/units'
    | '/app/workspace'
    | '/app/workspaces'
    | '/app'
    | '/app/unit/$unitId/access'
    | '/app/unit/$unitId/actions'
    | '/app/unit/$unitId/alerts'
    | '/app/unit/$unitId/billing'
    | '/app/unit/$unitId/control-room'
    | '/app/unit/$unitId/flows'
    | '/app/unit/$unitId'
    | '/app/unit/$unitId/systems/$systemId'
    | '/app/unit/$unitId/systems'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/console'
    | '/control-room'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/_authenticated/app'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/members'
    | '/_authenticated/app/units'
    | '/_authenticated/app/workspace'
    | '/_authenticated/app/workspaces'
    | '/_authenticated/app/'
    | '/_authenticated/app/unit/$unitId'
    | '/_authenticated/app/unit/$unitId/access'
    | '/_authenticated/app/unit/$unitId/actions'
    | '/_authenticated/app/unit/$unitId/alerts'
    | '/_authenticated/app/unit/$unitId/billing'
    | '/_authenticated/app/unit/$unitId/control-room'
    | '/_authenticated/app/unit/$unitId/flows'
    | '/_authenticated/app/unit/$unitId/systems'
    | '/_authenticated/app/unit/$unitId/'
    | '/_authenticated/app/unit/$unitId/systems/$systemId'
    | '/_authenticated/app/unit/$unitId/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  ControlRoomRoute: typeof ControlRoomRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/members': {
      id: '/_authenticated/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AuthenticatedAppMembersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/units': {
      id: '/_authenticated/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AuthenticatedAppUnitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workspace': {
      id: '/_authenticated/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workspaces': {
      id: '/_authenticated/app/workspaces'
      path: '/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AuthenticatedAppWorkspacesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/unit/$unitId': {
      id: '/_authenticated/app/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/app/unit/$unitId'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/unit/$unitId/': {
      id: '/_authenticated/app/unit/$unitId/'
      path: '/'
      fullPath: '/app/unit/$unitId/'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/access': {
      id: '/_authenticated/app/unit/$unitId/access'
      path: '/access'
      fullPath: '/app/unit/$unitId/access'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdAccessRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/actions': {
      id: '/_authenticated/app/unit/$unitId/actions'
      path: '/actions'
      fullPath: '/app/unit/$unitId/actions'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdActionsRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/alerts': {
      id: '/_authenticated/app/unit/$unitId/alerts'
      path: '/alerts'
      fullPath: '/app/unit/$unitId/alerts'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdAlertsRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/billing': {
      id: '/_authenticated/app/unit/$unitId/billing'
      path: '/billing'
      fullPath: '/app/unit/$unitId/billing'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdBillingRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/control-room': {
      id: '/_authenticated/app/unit/$unitId/control-room'
      path: '/control-room'
      fullPath: '/app/unit/$unitId/control-room'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdControlRoomRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/flows': {
      id: '/_authenticated/app/unit/$unitId/flows'
      path: '/flows'
      fullPath: '/app/unit/$unitId/flows'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdFlowsRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/systems': {
      id: '/_authenticated/app/unit/$unitId/systems'
      path: '/systems'
      fullPath: '/app/unit/$unitId/systems'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdSystemsRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdRoute
    }
    '/_authenticated/app/unit/$unitId/systems/': {
      id: '/_authenticated/app/unit/$unitId/systems/'
      path: '/'
      fullPath: '/app/unit/$unitId/systems/'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdSystemsIndexRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdSystemsRoute
    }
    '/_authenticated/app/unit/$unitId/systems/$systemId': {
      id: '/_authenticated/app/unit/$unitId/systems/$systemId'
      path: '/$systemId'
      fullPath: '/app/unit/$unitId/systems/$systemId'
      preLoaderRoute: typeof AuthenticatedAppUnitUnitIdSystemsSystemIdRouteImport
      parentRoute: typeof AuthenticatedAppUnitUnitIdSystemsRoute
    }
  }
}

interface AuthenticatedAppUnitUnitIdSystemsRouteChildren {
  AuthenticatedAppUnitUnitIdSystemsSystemIdRoute: typeof AuthenticatedAppUnitUnitIdSystemsSystemIdRoute
  AuthenticatedAppUnitUnitIdSystemsIndexRoute: typeof AuthenticatedAppUnitUnitIdSystemsIndexRoute
}

const AuthenticatedAppUnitUnitIdSystemsRouteChildren: AuthenticatedAppUnitUnitIdSystemsRouteChildren =
  {
    AuthenticatedAppUnitUnitIdSystemsSystemIdRoute:
      AuthenticatedAppUnitUnitIdSystemsSystemIdRoute,
    AuthenticatedAppUnitUnitIdSystemsIndexRoute:
      AuthenticatedAppUnitUnitIdSystemsIndexRoute,
  }

const AuthenticatedAppUnitUnitIdSystemsRouteWithChildren =
  AuthenticatedAppUnitUnitIdSystemsRoute._addFileChildren(
    AuthenticatedAppUnitUnitIdSystemsRouteChildren,
  )

interface AuthenticatedAppUnitUnitIdRouteChildren {
  AuthenticatedAppUnitUnitIdAccessRoute: typeof AuthenticatedAppUnitUnitIdAccessRoute
  AuthenticatedAppUnitUnitIdActionsRoute: typeof AuthenticatedAppUnitUnitIdActionsRoute
  AuthenticatedAppUnitUnitIdAlertsRoute: typeof AuthenticatedAppUnitUnitIdAlertsRoute
  AuthenticatedAppUnitUnitIdBillingRoute: typeof AuthenticatedAppUnitUnitIdBillingRoute
  AuthenticatedAppUnitUnitIdControlRoomRoute: typeof AuthenticatedAppUnitUnitIdControlRoomRoute
  AuthenticatedAppUnitUnitIdFlowsRoute: typeof AuthenticatedAppUnitUnitIdFlowsRoute
  AuthenticatedAppUnitUnitIdSystemsRoute: typeof AuthenticatedAppUnitUnitIdSystemsRouteWithChildren
  AuthenticatedAppUnitUnitIdIndexRoute: typeof AuthenticatedAppUnitUnitIdIndexRoute
}

const AuthenticatedAppUnitUnitIdRouteChildren: AuthenticatedAppUnitUnitIdRouteChildren =
  {
    AuthenticatedAppUnitUnitIdAccessRoute:
      AuthenticatedAppUnitUnitIdAccessRoute,
    AuthenticatedAppUnitUnitIdActionsRoute:
      AuthenticatedAppUnitUnitIdActionsRoute,
    AuthenticatedAppUnitUnitIdAlertsRoute:
      AuthenticatedAppUnitUnitIdAlertsRoute,
    AuthenticatedAppUnitUnitIdBillingRoute:
      AuthenticatedAppUnitUnitIdBillingRoute,
    AuthenticatedAppUnitUnitIdControlRoomRoute:
      AuthenticatedAppUnitUnitIdControlRoomRoute,
    AuthenticatedAppUnitUnitIdFlowsRoute: AuthenticatedAppUnitUnitIdFlowsRoute,
    AuthenticatedAppUnitUnitIdSystemsRoute:
      AuthenticatedAppUnitUnitIdSystemsRouteWithChildren,
    AuthenticatedAppUnitUnitIdIndexRoute: AuthenticatedAppUnitUnitIdIndexRoute,
  }

const AuthenticatedAppUnitUnitIdRouteWithChildren =
  AuthenticatedAppUnitUnitIdRoute._addFileChildren(
    AuthenticatedAppUnitUnitIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppMembersRoute: typeof AuthenticatedAppMembersRoute
  AuthenticatedAppUnitsRoute: typeof AuthenticatedAppUnitsRoute
  AuthenticatedAppWorkspaceRoute: typeof AuthenticatedAppWorkspaceRoute
  AuthenticatedAppWorkspacesRoute: typeof AuthenticatedAppWorkspacesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppUnitUnitIdRoute: typeof AuthenticatedAppUnitUnitIdRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppMembersRoute: AuthenticatedAppMembersRoute,
  AuthenticatedAppUnitsRoute: AuthenticatedAppUnitsRoute,
  AuthenticatedAppWorkspaceRoute: AuthenticatedAppWorkspaceRoute,
  AuthenticatedAppWorkspacesRoute: AuthenticatedAppWorkspacesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppUnitUnitIdRoute: AuthenticatedAppUnitUnitIdRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  ControlRoomRoute: ControlRoomRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
